import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import type { NextApiRequest, NextApiResponse } from 'next'

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

 
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const doc = new GoogleSpreadsheet('1iErjwRDwq-ruQuLY9fNMz_xGTKlPO_fwAvD2RkrYUys', serviceAccountAuth);
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByTitle['시트1']; 
  const rows = await sheet.getRows();

  const lastRow = rows.pop();

  if (!lastRow) return res.status(404);

  const values = Object.values(lastRow.toObject());

  return res.status(200).json(
    {
      date: values[1],
      count: values[0]
    }
  );
}