import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';
import type { NextApiRequest, NextApiResponse } from 'next'

const serviceAccountAuth = new JWT({
  // env var values here are copied from service account credentials generated by google
  // see "Authentication" section in docs for more info
  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
  key: process.env.GOOGLE_PRIVATE_KEY,
  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
});

 
export default async function handler(
  req: NextApiRequest,
  res: NextApiResponse
) {
  const doc = new GoogleSpreadsheet('1iErjwRDwq-ruQuLY9fNMz_xGTKlPO_fwAvD2RkrYUys', serviceAccountAuth);
  await doc.loadInfo(); // loads document properties and worksheets
  const sheet = doc.sheetsByTitle['시트1']; 
  const rows = await sheet.getRows(); 

  const formattedRows = rows.map((row) => { 
    const values = Object.values(row.toObject());
    const date = values[1]; // FIXME
    const count = values[0]; // FIXME
  
    return { date, count }
  }); // 데이터 형식 변환 (필요에 따라 수정)

  res.status(200).json(formattedRows);
}